Location Based Restrictions
matsim-org/matsim-episim-libs pull request #72
Opened 2021-04-20 22:49 UTC by jakobrehmann

This PR adds the functionality of location based restrictions. The allows different districts or neighborhoods to have varying values for activity reduction. For instance, the activity reduction for workplaces in Berlin-Spandau may be different than for workplaces in Berlin-Mitte. So far, these location based restrictions kick in for activities, but not yet for the trips between activities.

2021-04-21 09:40 UTC, rakow commented on src/main/java/org/matsim/episim/model/AbstractContactModel.java
> +	private Map<String, String> subdistrictFacilities;
Could be final maybe?

2021-04-21 13:33 UTC, rakow commented on src/main/java/org/matsim/run/modules/SnzBerlinScenario25pct2020JR.java
> +public final class SnzBerlinScenario25pct2020JR extends AbstractSnzScenario2020 {
Do you need a copy of the whole file? It is possible to extend/delegate to the existing scenario and only make additional changes?

2021-04-21 13:35 UTC, rakow commented on src/main/java/org/matsim/scenarioCreation/ZipcodeAndSubdistrictLookup.java
> +	public static final class Index {
This class already exists somewhere else. Please try to reuse the existing one.

2021-04-21 13:35 UTC, rakow requested changes
Please see individual comments for some remarks. Also the tests need to pass first.

2021-04-29 11:22 UTC, rakow reviewed
Looks good so far! Could you add/extend the Restriction test to account for the new
districtSpecificValue?

2021-05-12 22:08 UTC, jakobrehmann commented
Thanks for your feedback and review @rakow . locationBasedRestriction functionality is now tested on various levels:

1) Restriction: checks that cloning, updating, and merging of works correctly for district specific restrictions;

2) FixedPolicy: checks that the config builder correctly builds fixed policies; and

3) DefaultContactModel: Checks that the districtSpecificValue is used for remaining fraction if a container is in the corresponding district, and that the default remaining fraction is used if not.

The location based functionality still lives within the AbstractContactModel, so it should be theoretically available to all contact models; however, the constructor for each implementation must be changed to accept a Scenario (containing activity facilities) for the functionality to perform as intended. I've done this change for the DefaultContactModel and the SymmetricContactModel. Is there a more elegant solution you can think of?

2021-05-31 08:31 UTC, rakow commented
Is it ready to merge? Still marked as draft currently.

2021-06-01 16:10 UTC, jakobrehmann commented
Several things have been updated:
- location based restrictions can now be processed when ActivityHandling==startOfDay. This was done by adding a LocationBasedParticipationModel. A corresponding test was also created. 
- The merging behavior for locationBasedRf was modified: If user manually adds restriction for remaining fraction, the previous locationBasedRf will be deleted. For instance, if work activity levels are manually reduced for a holiday, the old locationBasedRf should not kept, since it still contains the higher activity levels.  
- In CreateRestrictionsFromCSV, the extrapolation function was expanded with respect to location based restrictions.
- districtSpecificValue was refactored to locationBasedRf for clarity-sake.

2021-06-02 09:05 UTC, jakobrehmann reviewed
it can be removed

2021-06-02 09:48 UTC, rakow approved these changes
Very good work, thank you @jakobrehmann !

2021-06-02 09:48 UTC, merged